"""Estructura inicial con campos nuevos

Revision ID: 3aa3ee4ad497
Revises: 
Create Date: 2025-10-28 04:34:28.136092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3aa3ee4ad497'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matriculas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monto_inicial', sa.Float(), nullable=False))

    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('es_pago_inicial', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('monto_inicial', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.drop_column('monto_inicial')
        batch_op.drop_column('es_pago_inicial')

    with op.batch_alter_table('matriculas', schema=None) as batch_op:
        batch_op.drop_column('monto_inicial')

    # ### end Alembic commands ###
